
project_id = "wxyotttvyexxzeaewyga"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
allowed_mime_types = ["image/png", "image/jpg", "image/jpeg", "image/gif", "image/webp"]

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.get-stripe-keys]
verify_jwt = true

[functions.stripe-webhook-secure]
verify_jwt = false

[functions.process-webhook-retries]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.public-stripe-settings]
verify_jwt = false

[functions.locks]
verify_jwt = false

[functions.locks-cleaner]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[edge_runtime]
enabled = true
policy = "per_request"
