// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxyotttvyexxzeaewyga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4eW90dHR2eWV4eHplYWV3eWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTU3NDEsImV4cCI6MjA2NzEzMTc0MX0.QDugoBTZMxFTB79_tD-6Ng4_DYZpSmuCzm3y8yLw34U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ✅ GUARDRAIL 2: Dev-only base table detection (fail fast if base tables queried from client)
if (import.meta.env.DEV) {
  const originalFrom = supabase.from.bind(supabase);
  (supabase as any).from = function(table: string) {
    const restrictedBaseTables = ['services', 'booking_windows', 'venues', 'venue_stripe_settings'];
    const allowedPublicViews = ['services_public', 'booking_windows_public', 'venues_public'];
    
    if (restrictedBaseTables.includes(table) && !allowedPublicViews.includes(table)) {
      console.error(`🚨 DEV WARNING: Querying base table "${table}" from client!`);
      console.error(`Use "${table}_public" view instead for security.`);
      throw new Error(
        `Security violation: Client should query "${table}_public" view, not base table "${table}". ` +
        `This prevents exposing sensitive data to anonymous users.`
      );
    }
    
    return originalFrom(table);
  };
  
  console.log('🛡️ Base table detection enabled in DEV mode');
}