// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxyotttvyexxzeaewyga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4eW90dHR2eWV4eHplYWV3eWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTU3NDEsImV4cCI6MjA2NzEzMTc0MX0.QDugoBTZMxFTB79_tD-6Ng4_DYZpSmuCzm3y8yLw34U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ✅ GUARDRAIL 2: Dev-only base table detection (authentication-aware)
if (import.meta.env.DEV) {
  const originalFrom = supabase.from.bind(supabase);
  (supabase as any).from = function(table: string) {
    const restrictedBaseTables = ['services', 'booking_windows', 'venues', 'venue_stripe_settings'];
    const allowedPublicViews = ['services_public', 'booking_windows_public', 'venues_public'];
    
    if (restrictedBaseTables.includes(table) && !allowedPublicViews.includes(table)) {
      // Check authentication status asynchronously
      supabase.auth.getSession().then(({ data: { session } }) => {
        if (!session) {
          console.error(`🚨 DEV WARNING: Anonymous user querying base table "${table}"!`);
          console.error(`Use "${table}_public" view instead for security.`);
          console.error(
            `Security violation: Anonymous users should query "${table}_public" view, not base table "${table}". ` +
            `This prevents exposing sensitive data to unauthenticated users.`
          );
        } else {
          console.log(`🔐 Authenticated user querying "${table}" (RLS enforced)`);
        }
      });
    }
    
    return originalFrom(table);
  };
  
  console.log('🛡️ Authentication-aware base table guardrail enabled in DEV mode');
}