// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxyotttvyexxzeaewyga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4eW90dHR2eWV4eHplYWV3eWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTU3NDEsImV4cCI6MjA2NzEzMTc0MX0.QDugoBTZMxFTB79_tD-6Ng4_DYZpSmuCzm3y8yLw34U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});